var mes = 9

if(mes == 1)
    console.log("Janeiro, tem 31 dias")
else if(mes == 2)
    console.log("Fevereiro, tem 28 dias")
else if(mes == 3)
    console.log("Março, tem 31 dias")
else if(mes == 4)
    console.log("Abril, tem 30 dias")
else if(mes == 5)
    console.log("Maio, tem 31 dias")
else if(mes == 6)
    console.log("Junho, tem 30 dias")
else if(mes == 7)
    console.log("Julho, tem 30 dias")
else if(mes == 8)
    console.log("Agosto, tem 31 dias")
else if(mes == 9)
    console.log("Setembro, tem 30 dias")
else if(mes == 10)
    console.log("Outubro, tem 31 dias")
else if(mes == 11)
    console.log("Novembro, tem 30 dias")
else if(mes == 12)
    console.log("Dezembro, tem 31 dias")
else
    console.log("Mês não encontrado")